spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb
    username: sa
    password:

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: name
  default-produces-media-type: application/json

logging:
  config: classpath:logback-dev.xml

file:
  upload:
    location: /app/file
    temp: temp/
    public-url: http://localhost
    private-url: http://localhost